# -*- coding:utf-8 -*-
html_doc = """


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="ctl00_Head1"><title>
	三峡大学教务管理系统
</title><link href="../Images/Default.css" rel="stylesheet" type="text/css" />

<script language="javascript" type="text/javascript">
// <!CDATA[

function window_onkeydown() {
//window.alert(event.keyCode);
if ((event.altKey)||((event.keyCode==8)&&(event.srcElement.type!="text"&&event.srcElement.type!="textarea"&&event.srcElement.type!="password"))||((event.ctrlKey)&&((event.keyCode==78)||(event.keyCode==82)))||(event.keyCode==116))
{

event.keyCode=0;
event.returnValue=false;
}
}

// ]]>
</script>
<style type="text/css">
	.ctl00_Menu2_0 { background-color:white;visibility:hidden;display:none;position:absolute;left:0px;top:0px; }
	.ctl00_Menu2_1 { text-decoration:none; }
	.ctl00_Menu2_2 { background-color:Red; }
	.ctl00_Menu1_0 { background-color:white;visibility:hidden;display:none;position:absolute;left:0px;top:0px; }
	.ctl00_Menu1_1 { text-decoration:none; }
	.ctl00_Menu1_2 {  }

</style></head>
<body onkeydown="return window_onkeydown()">
    <form name="aspnetForm" method="post" action="PlanToStudy_Query.aspx" id="aspnetForm">
<div>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKLTg3MTIxNzAzNA9kFgJmD2QWAgIDD2QWCAIFDw8WAh4EVGV4dAUTMjAxMjEzNjEyMeWQtOWMluWQiWRkAgcQPCsADQIADxYCHgtfIURhdGFCb3VuZGdkDBQrAAIFAzA6MBQrAAIWEB8ABQzlrabkuJrpooToraYeBVZhbHVlBQzlrabkuJrpooToraYeC05hdmlnYXRlVXJsBR4vandjX2dseHQvU2l0ZU1hcC9UZXN0LmFzcHgjMzIeB1Rvb2xUaXAFDOWtpuS4mumihOitph4HRW5hYmxlZGceClNlbGVjdGFibGVnHghEYXRhUGF0aAUeL2p3Y19nbHh0L3NpdGVtYXAvdGVzdC5hc3B4IzMyHglEYXRhQm91bmRnFCsABAULMDowLDA6MSwwOjIUKwACFhAfAAUQ4peGIOWfueWFu+iuoeWIkh8CBRDil4Yg5Z+55YW76K6h5YiSHwMFKS9qd2NfZ2x4dC9QbGFuX1RyYWluL1BsYW5UcmFpbl9RdWVyeS5hc3B4HwQFDOWfueWFu+iuoeWIkh8FZx8GZx8HBSkvandjX2dseHQvcGxhbl90cmFpbi9wbGFudHJhaW5fcXVlcnkuYXNweB8IZ2QUKwACFhIfAgUQ4peGIOWtpuS4muavlOWvuR8IZx4IU2VsZWN0ZWRnHwAFEOKXhiDlrabkuJrmr5Tlr7kfAwUuL2p3Y19nbHh0L1BsYW5fVG9fU3R1ZHkvUGxhblRvU3R1ZHlfUXVlcnkuYXNweB8FZx8GZx8EBQzlrabkuJrmr5Tlr7kfBwUuL2p3Y19nbHh0L3BsYW5fdG9fc3R1ZHkvcGxhbnRvc3R1ZHlfcXVlcnkuYXNweGQUKwACFhAfAAUQ4peGIOWtpuS4mumihOitph8CBRDil4Yg5a2m5Lia6aKE6K2mHwMFKy9qd2NfZ2x4dC9QbGFuX1RvX1N0dWR5L1N0dWR5X1dhcm5uaW5nLmFzcHgfBAUM5a2m5Lia6aKE6K2mHwVnHwZnHwcFKy9qd2NfZ2x4dC9wbGFuX3RvX3N0dWR5L3N0dWR5X3dhcm5uaW5nLmFzcHgfCGdkZGQCCRA8KwANAgAPFgIfAWdkDBQrAAcFFzA6MCwwOjEsMDoyLDA6MywwOjQsMDo1FCsAAhYQHwAFESB8IHwg5Y2z5pe25LqL5YqhHwIFESB8IHwg5Y2z5pe25LqL5YqhHwMFJi9qd2NfZ2x4dC9TdHVfTm90aWNlL05vdGljZV9RdWVyeS5hc3B4HwQFFeWQhOexu+mAmuefpeWPiuS6i+WKoR8FZx8GZx8HBSYvandjX2dseHQvc3R1X25vdGljZS9ub3RpY2VfcXVlcnkuYXNweB8IZ2QUKwACFhAfAAURIHwgfCDlrabnlJ/pgInor74fAgURIHwgfCDlrabnlJ/pgInor74fAwUbL2p3Y19nbHh0L1NpdGVNYXAvVGVzdC5hc3B4HwQFDOWtpueUn+mAieivvh8FZx8GZx8HBRsvandjX2dseHQvc2l0ZW1hcC90ZXN0LmFzcHgfCGcUKwAGBRMwOjAsMDoxLDA6MiwwOjMsMDo0FCsAAhYQHwAFE+KXhiDor77nqIvmn6Xor6LjgIAfAgUT4peGIOivvueoi+afpeivouOAgB8DBSkvandjX2dseHQvQ291cnNlX0Nob2ljZS9Db3Vyc2VfUXVlcnkuYXNweB8EBRXlvIDorr7nmoTor77nqIvmn6Xor6IfBWcfBmcfBwUpL2p3Y19nbHh0L2NvdXJzZV9jaG9pY2UvY291cnNlX3F1ZXJ5LmFzcHgfCGdkFCsAAhYQHwAFE+KXhiDlrabnlJ/pgInor77jgIAfAgUT4peGIOWtpueUn+mAieivvuOAgB8DBSovandjX2dseHQvQ291cnNlX0Nob2ljZS9Db3Vyc2VfQ2hvaWNlLmFzcHgfBAUM5a2m55Sf6YCJ6K++HwVnHwZnHwcFKi9qd2NfZ2x4dC9jb3Vyc2VfY2hvaWNlL2NvdXJzZV9jaG9pY2UuYXNweB8IZ2QUKwACFhAfAAUT4peGIOWtpueUn+mAgOivvuOAgB8CBRPil4Yg5a2m55Sf6YCA6K++44CAHwMFKy9qd2NfZ2x4dC9Db3Vyc2VfQ2hvaWNlL0NvdXJzZV9BYmFuZG9uLmFzcHgfBAUM5a2m55Sf6YCA6K++HwVnHwZnHwcFKy9qd2NfZ2x4dC9jb3Vyc2VfY2hvaWNlL2NvdXJzZV9hYmFuZG9uLmFzcHgfCGdkFCsAAhYQHwAFE+KXhiDpgInkv67or77ooajjgIAfAgUT4peGIOmAieS/ruivvuihqOOAgB8DBSwvandjX2dseHQvQ291cnNlX0Nob2ljZS9Db3Vyc2VfU2NoZWR1bGUuYXNweB8EBQzpgInkv67or77ooagfBWcfBmcfBwUsL2p3Y19nbHh0L2NvdXJzZV9jaG9pY2UvY291cnNlX3NjaGVkdWxlLmFzcHgfCGdkFCsAAhYQHwAFE+KXhiDlt7LpgInor77nqIvjgIAfAgUT4peGIOW3sumAieivvueoi+OAgB8DBS0vandjX2dseHQvQ291cnNlX0Nob2ljZS9TdHVfQ291cnNlX1F1ZXJ5LmFzcHgfBAUV5bey6YCJ5L+u6K++56iL5p+l6K+iHwVnHwZnHwcFLS9qd2NfZ2x4dC9jb3Vyc2VfY2hvaWNlL3N0dV9jb3Vyc2VfcXVlcnkuYXNweB8IZ2QUKwACFhAfAAURIHwgfCDmiJDnu6nmn6Xor6IfAgURIHwgfCDmiJDnu6nmn6Xor6IfAwUdL2p3Y19nbHh0L1NpdGVNYXAvVGVzdC5hc3B4IzMfBAUS5a2m55Sf5oiQ57up5p+l6K+iHwVnHwZnHwcFHS9qd2NfZ2x4dC9zaXRlbWFwL3Rlc3QuYXNweCMzHwhnFCsAAwUHMDowLDA6MRQrAAIWEB8ABRHil4Yg5oiQ57up5p+l6K+iIB8CBRHil4Yg5oiQ57up5p+l6K+iIB8DBSgvandjX2dseHQvU3R1ZGVudF9TY29yZS9TY29yZV9RdWVyeS5hc3B4HwQFDOaIkOe7qeafpeivoh8FZx8GZx8HBSgvandjX2dseHQvc3R1ZGVudF9zY29yZS9zY29yZV9xdWVyeS5hc3B4HwhnZBQrAAIWEB8ABRTil4Yg5Y+M5a2m5L2N5oiQ57upIB8CBRTil4Yg5Y+M5a2m5L2N5oiQ57upIB8DBTEvandjX2dseHQvRG91YmxlRGVncmVlX1Njb3JlL0RibERlZ3JlZV9TY29yZS5hc3B4HwQFFeWPjOWtpuS9jeaIkOe7qeafpeivoh8FZx8GZx8HBTEvandjX2dseHQvZG91YmxlZGVncmVlX3Njb3JlL2RibGRlZ3JlZV9zY29yZS5hc3B4HwhnZBQrAAIWEB8ABREgfCB8IOWQhOexu+aKpeWQjR8CBREgfCB8IOWQhOexu+aKpeWQjR8DBR0vandjX2dseHQvU2l0ZU1hcC9UZXN0LmFzcHgjNR8EBQzlkITnsbvmiqXlkI0fBWcfBmcfBwUdL2p3Y19nbHh0L3NpdGVtYXAvdGVzdC5hc3B4IzUfCGcUKwAIBRswOjAsMDoxLDA6MiwwOjMsMDo0LDA6NSwwOjYUKwACFhAfAAUR4peGIOetiee6p+iAg+ivlSAfAgUR4peGIOetiee6p+iAg+ivlSAfAwUlL2p3Y19nbHh0L2NldF9zeXN0ZW0vc3R1ZGVudF9jZXQuYXNweB8EBRLnrYnnuqfogIPor5XmiqXlkI0fBWcfBmcfBwUlL2p3Y19nbHh0L2NldF9zeXN0ZW0vc3R1ZGVudF9jZXQuYXNweB8IZ2QUKwACFhAfAAUR4peGIOWQjeWNleafpeivoiAfAgUR4peGIOWQjeWNleafpeivoiAfAwUmL2p3Y19nbHh0L2NldF9zeXN0ZW0vc3R1ZGVudF9MaXN0LmFzcHgfBAUe562J57qn6ICD6K+V5oql5ZCN5ZCN5Y2V5p+l6K+iHwVnHwZnHwcFJi9qd2NfZ2x4dC9jZXRfc3lzdGVtL3N0dWRlbnRfbGlzdC5hc3B4HwhnZBQrAAIWEB8ABRDil4Yg5q+V5Lia6K6+6K6hHwIFEOKXhiDmr5XkuJrorr7orqEfAwUtL2p3Y19nbHh0L0dyYWR1RGVzaWduX3N5c3RlbS9HcmFkdURlc2lnbi5hc3B4HwQFGOavleS4muiuvuiuoeivvumimOeUs+aKpR8FZx8GZx8HBS0vandjX2dseHQvZ3JhZHVkZXNpZ25fc3lzdGVtL2dyYWR1ZGVzaWduLmFzcHgfCGdkFCsAAhYQHwAFEOKXhiDph43kv67miqXlkI0fAgUQ4peGIOmHjeS/ruaKpeWQjR8DBSgvandjX2dseHQvUmVwZWF0X1N0dWR5L1JlcGVhdF9TdHVkeS5hc3B4HwQFDOmHjeS/ruaKpeWQjR8FZx8GZx8HBSgvandjX2dseHQvcmVwZWF0X3N0dWR5L3JlcGVhdF9zdHVkeS5hc3B4HwhnZBQrAAIWEB8ABRDil4Yg6YeN6ICD5oql5ZCNHwIFEOKXhiDph43ogIPmiqXlkI0fAwUmL2p3Y19nbHh0L1JlcGVhdF9FeGFtL1JlcGVhdF9FeGFtLmFzcHgfBAUM6YeN6ICD5oql5ZCNHwVnHwZnHwcFJi9qd2NfZ2x4dC9yZXBlYXRfZXhhbS9yZXBlYXRfZXhhbS5hc3B4HwhnZBQrAAIWEB8ABRDil4Yg5riF55CG6ICD6K+VHwIFEOKXhiDmuIXnkIbogIPor5UfAwUkL2p3Y19nbHh0L0NsZWFyX0V4YW0vQ2xlYXJfRXhhbS5hc3B4HwQFEua4heeQhuiAg+ivleaKpeWQjR8FZx8GZx8HBSQvandjX2dseHQvY2xlYXJfZXhhbS9jbGVhcl9leGFtLmFzcHgfCGdkFCsAAhYQHwAFFuKXhiDnrKzkuozlrabkvY3miqXlkI0fAgUW4peGIOesrOS6jOWtpuS9jeaKpeWQjR8DBSovandjX2dseHQvRG91YmxlX0RlZ3JlZS9Eb3VibGVfRGVncmVlLmFzcHgfBAUP5Y+M5a2m5L2N5oql5ZCNHwVnHwZnHwcFKi9qd2NfZ2x4dC9kb3VibGVfZGVncmVlL2RvdWJsZV9kZWdyZWUuYXNweB8IZ2QUKwACFhAfAAURIHwgfCDlrabnlJ/or4TmlZkfAgURIHwgfCDlrabnlJ/or4TmlZkfAwUkL2p3Y19nbHh0L1N0dV9Bc3Nlc3MvU3R1X0Fzc2Vzcy5hc3B4HwQFDOWtpueUn+ivhOaVmR8FZx8GZx8HBSQvandjX2dseHQvc3R1X2Fzc2Vzcy9zdHVfYXNzZXNzLmFzcHgfCGdkFCsAAhYQHwAFESB8IHwg5Liq5Lq65L+h5oGvHwIFESB8IHwg5Liq5Lq65L+h5oGvHwMFHS9qd2NfZ2x4dC9TaXRlTWFwL1Rlc3QuYXNweCMxHwQFDOS4quS6uuS/oeaBrx8FZx8GZx8HBR0vandjX2dseHQvc2l0ZW1hcC90ZXN0LmFzcHgjMR8IZxQrAAQFCzA6MCwwOjEsMDoyFCsAAhYQHwAFEOKXhiDkuKrkurrkv6Hmga8fAgUQ4peGIOS4quS6uuS/oeaBrx8DBSAvandjX2dseHQvU3R1X0luZm8vU3R1X2luZm8uYXNweB8EBRjlrabnlJ/kuKrkurrkv6Hmga/mn6Xor6IfBWcfBmcfBwUgL2p3Y19nbHh0L3N0dV9pbmZvL3N0dV9pbmZvLmFzcHgfCGdkFCsAAhYQHwAFEOKXhiDkv6Hmga/kv67mlLkfAgUQ4peGIOS/oeaBr+S/ruaUuR8DBSYvandjX2dseHQvU3R1X0luZm8vU3R1aW5mb19Nb2RpZnkuYXNweB8EBRjlrabnlJ/kuKrkurrkv6Hmga/kv67mlLkfBWcfBmcfBwUmL2p3Y19nbHh0L3N0dV9pbmZvL3N0dWluZm9fbW9kaWZ5LmFzcHgfCGdkFCsAAhYQHwAFEOKXhiDlr4bnoIHkv67mlLkfAgUQ4peGIOWvhueggeS/ruaUuR8DBSQvandjX2dseHQvU3R1X0luZm8vU3R1X1Bhc3N3b3JkLmFzcHgfBAUY5a2m55Sf55So5oi35a+G56CB5L+u5pS5HwVnHwZnHwcFJC9qd2NfZ2x4dC9zdHVfaW5mby9zdHVfcGFzc3dvcmQuYXNweB8IZ2RkZAILD2QWBAIBDzwrAA0BAA8WCB8BZx4JUGFnZUNvdW50AgEeC18hSXRlbUNvdW50AloeB0NhcHRpb25lZBYCZg9kFrYBAgEPZBYUZg8PFgIfAAUFRzAwMDFkZAIBDw8WAh8ABQbkvZPogrJkZAICDw8WAh8ABQIzMGRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjc5ZGQCCQ8PFgIfAAUBMWRkAgIPZBYUZg8PFgIfAAUFRzAwMDFkZAIBDw8WAh8ABQbkvZPogrJkZAICDw8WAh8ABQIzMGRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjY1ZGQCCQ8PFgIfAAUBMWRkAgMPZBYUZg8PFgIfAAUFRzAwMDFkZAIBDw8WAh8ABQbkvZPogrJkZAICDw8WAh8ABQIzMGRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEyZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjY1ZGQCCQ8PFgIfAAUBMWRkAgQPZBYUZg8PFgIfAAUFRzAwMDFkZAIBDw8WAh8ABQbkvZPogrJkZAICDw8WAh8ABQIzMGRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjY1ZGQCCQ8PFgIfAAUBMWRkAgUPZBYUZg8PFgIfAAUFSDAwMDFkZAIBDw8WAh8ABQ/orqHnrpfmnLrln7rnoYBkZAICDw8WAh8ABQI0OGRkAgMPDxYCHwAFATNkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEyZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjg0ZGQCCQ8PFgIfAAUBM2RkAgYPZBYUZg8PFgIfAAUFSDEwMDVkZAIBDw8WAh8ABRND6K+t6KiA56iL5bqP6K6+6K6hZGQCAg8PFgIfAAUCNjRkZAIDDw8WAh8ABQE0ZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxMmRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI2MGRkAgkPDxYCHwAFATRkZAIHD2QWFGYPDxYCHwAFBVAwMDAxZGQCAQ8PFgIfAAUW5aSn5a2m6Iux6K+tMee6p+WQrOivtGRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTJkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCNzhkZAIJDw8WAh8ABQEyZGQCCA9kFhRmDw8WAh8ABQVQMDAwMmRkAgEPDxYCHwAFFuWkp+WtpuiLseivrTHnuqfor7vlhplkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEyZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjY2ZGQCCQ8PFgIfAAUBMmRkAgkPZBYUZg8PFgIfAAUFUDAwMDNkZAIBDw8WAh8ABRblpKflraboi7Hor60y57qn5ZCs6K+0ZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI2OWRkAgkPDxYCHwAFATJkZAIKD2QWFGYPDxYCHwAFBVAwMDA0ZGQCAQ8PFgIfAAUW5aSn5a2m6Iux6K+tMue6p+ivu+WGmWRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNjlkZAIJDw8WAh8ABQEyZGQCCw9kFhRmDw8WAh8ABQVQMDAwNWRkAgEPDxYCHwAFFuWkp+WtpuiLseivrTPnuqflkKzor7RkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBM2RkAggPDxYGHwAFAjYwHglCYWNrQ29sb3IKJR4EXyFTQgIIZGQCCQ8PFgIfAAUBMmRkAgwPZBYUZg8PFgIfAAUFUDAwMDZkZAIBDw8WAh8ABRblpKflraboi7Hor60z57qn6K+75YaZZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI2OWRkAgkPDxYCHwAFATJkZAIND2QWFGYPDxYCHwAFBVAwMDA3ZGQCAQ8PFgIfAAUW5aSn5a2m6Iux6K+tNOe6p+WQrOivtGRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQExZGQCCA8PFgYfAAUCNjAfDQolHw4CCGRkAgkPDxYCHwAFATJkZAIOD2QWFGYPDxYCHwAFBVAwMDA4ZGQCAQ8PFgIfAAUW5aSn5a2m6Iux6K+tNOe6p+ivu+WGmWRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNzRkZAIJDw8WAh8ABQEyZGQCDw9kFg5mDw8WAh8ABQVQMTIwMmRkAgEPDxYCHwAFFuWkp+WtpuiLseivrTXnuqflkKzor7RkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXlhajmoKHlhazlhbHlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIIDw8WBh8ABQnmnKrkv67kuaAfDQqNAR8OAghkZAIQD2QWDmYPDxYCHwAFBVAxMjAzZGQCAQ8PFgIfAAUW5aSn5a2m6Iux6K+tNee6p+ivu+WGmWRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAggPDxYGHwAFCeacquS/ruS5oB8NCo0BHw4CCGRkAhEPZBYUZg8PFgIfAAUFUTAwMDVkZAIBDw8WAh8ABQzlhpvkuovnkIborrpkZAICDw8WAh8ABQE4ZGQCAw8PFgIfAAUDMC41ZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxMmRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI3OGRkAgkPDxYCHwAFAzAuNWRkAhIPZBYUZg8PFgIfAAUFUTAwMDZkZAIBDw8WAh8ABQzlhpvkuovorq3nu4NkZAICDw8WAh8ABQIyd2RkAgMPDxYCHwAFAzIuNWRkAgQPDxYCHwAFFeWFqOagoeWFrOWFseW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTJkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODhkZAIJDw8WAh8ABQMyLjVkZAITD2QWFGYPDxYCHwAFBVkwMDAxZGQCAQ8PFgIfAAUb6ams5YWL5oCd5Li75LmJ5Z+65pys5Y6f55CGZGQCAg8PFgIfAAUCNDhkZAIDDw8WAh8ABQEzZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxMmRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI3NmRkAgkPDxYCHwAFATNkZAIUD2QWFGYPDxYCHwAFBVkwMDAyZGQCAQ8PFgIfAAUY5Lit5Zu96L+R546w5Luj5Y+y57qy6KaBZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI3MWRkAgkPDxYCHwAFATJkZAIVD2QWFGYPDxYCHwAFBVkwMDA0ZGQCAQ8PFgIfAAU85q+b5rO95Lic5oCd5oOz5ZKM5Lit5Zu954m56Imy56S+5Lya5Li75LmJ55CG6K665L2T57O75qaC6K66ZGQCAg8PFgIfAAUCOTZkZAIDDw8WAh8ABQE0ZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5pivZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI4NGRkAgkPDxYCHwAFATRkZAIWD2QWFGYPDxYCHwAFBVkwMDEyZGQCAQ8PFgIfAAUh5oCd5oOz6YGT5b635L+u5YW75LiO5rOV5b6L5Z+656GAZGQCAg8PFgIfAAUCNDhkZAIDDw8WAh8ABQEzZGQCBA8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4M2RkAgkPDxYCHwAFATNkZAIXD2QWFGYPDxYCHwAFBUMxMTQ2ZGQCAQ8PFgIfAAUb55S16Lev5LiO5qih5ouf55S15a2Q5oqA5pyvZGQCAg8PFgIfAAUCNzJkZAIDDw8WAh8ABQM0LjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjY1ZGQCCQ8PFgIfAAUDNC41ZGQCGA9kFhRmDw8WAh8ABQVDODA3M2RkAgEPDxYCHwAFIeeUtei3r+S4juaooeaLn+eUteWtkOaKgOacr+WunumqjGRkAgIPDxYCHwAFAjE2ZGQCAw8PFgIfAAUBMWRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTJkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODhkZAIJDw8WAh8ABQExZGQCGQ9kFhRmDw8WAh8ABQVGMDAwMWRkAgEPDxYCHwAFFOmrmOetieaVsOWtpuKFoCjkuIApZGQCAg8PFgIfAAUCODhkZAIDDw8WAh8ABQM1LjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPmmK9kZAIGDw8WAh8ABQQyMDEyZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjY4ZGQCCQ8PFgIfAAUDNS41ZGQCGg9kFhRmDw8WAh8ABQVGMDAwMmRkAgEPDxYCHwAFFOmrmOetieaVsOWtpuKFoCjkuowpZGQCAg8PFgIfAAUCODhkZAIDDw8WAh8ABQM1LjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPmmK9kZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjYwZGQCCQ8PFgIfAAUDNS41ZGQCGw9kFhRmDw8WAh8ABQVGMDAwN2RkAgEPDxYCHwAFD+e6v+aAp+S7o+aVsOKFoGRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNjlkZAIJDw8WAh8ABQEyZGQCHA9kFhRmDw8WAh8ABQVGMDAwOWRkAgEPDxYCHwAFD+amgueOh+e7n+iuoeKFoGRkAgIPDxYCHwAFAjQwZGQCAw8PFgIfAAUDMi41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI2MmRkAgkPDxYCHwAFAzIuNWRkAh0PZBYUZg8PFgIfAAUFRjAwMTJkZAIBDw8WAh8ABRTlpKflrabniannkIbihaAo5LiAKWRkAgIPDxYCHwAFAjU2ZGQCAw8PFgIfAAUDMy41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI2MWRkAgkPDxYCHwAFAzMuNWRkAh4PZBYUZg8PFgIfAAUFRjAwMTNkZAIBDw8WAh8ABRTlpKflrabniannkIbihaAo5LqMKWRkAgIPDxYCHwAFAjQ4ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCNjVkZAIJDw8WAh8ABQEzZGQCHw9kFhRmDw8WAh8ABQVIMTA0OWRkAgEPDxYCHwAFD+iuoeeul+acuue9kee7nGRkAgIPDxYCHwAFAjQ4ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+aYr2RkAgYPDxYCHwAFBDIwMTVkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNjZkZAIJDw8WAh8ABQEzZGQCIA9kFhRmDw8WAh8ABQVIMTA4NmRkAgEPDxYCHwAFDOaVsOaNrue7k+aehGRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQExZGQCCA8PFgYfAAUCNDEfDQqNAR8OAghkZAIJDw8WAh8ABQEwZGQCIQ9kFhRmDw8WAh8ABQVIMTA5MWRkAgEPDxYCHwAFEuaVsOWtl+WbvuWDj+WkhOeQhmRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODNkZAIJDw8WAh8ABQEyZGQCIg9kFhRmDw8WAh8ABQVIMTA5NGRkAgEPDxYCHwAFEumaj+acuuS/oeWPt+WIhuaekGRkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNjNkZAIJDw8WAh8ABQEyZGQCIw9kFhRmDw8WAh8ABQVIMTA5NmRkAgEPDxYCHwAFD+mAmuS/oeWOn+eQhuKFoGRkAgIPDxYCHwAFAjcyZGQCAw8PFgIfAAUDNC41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5pivZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATNkZAIIDw8WBh8ABQI2MB8NCiUfDgIIZGQCCQ8PFgIfAAUDNC41ZGQCJA9kFhRmDw8WAh8ABQVIMTEwNmRkAgEPDxYCHwAFFeW+ruWei+iuoeeul+acuuaKgOacr2RkAgIPDxYCHwAFAjY0ZGQCAw8PFgIfAAUBNGRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+aYr2RkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQEzZGQCCA8PFgYfAAUCNjAfDQolHw4CCGRkAgkPDxYCHwAFATRkZAIlD2QWFGYPDxYCHwAFBUgxMTEzZGQCAQ8PFgIfAAUP5L+h5Y+35LiO57O757ufZGQCAg8PFgIfAAUCNzJkZAIDDw8WAh8ABQM0LjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPmmK9kZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBM2RkAggPDxYGHwAFAjI3Hw0KjQEfDgIIZGQCCQ8PFgIfAAUBMGRkAiYPZBYUZg8PFgIfAAUFSDExOTlkZAIBDw8WAh8ABSDpgJrkv6Hlt6XnqIvlrabnp5HmpoLorroo5Y+M6K+tKWRkAgIPDxYCHwAFAThkZAIDDw8WAh8ABQMwLjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEyZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjk0ZGQCCQ8PFgIfAAUDMC41ZGQCJw9kFhRmDw8WAh8ABQVIMTIxNWRkAgEPDxYCHwAFEumAmuS/oeeUteWtkOe6v+i3r2RkAgIPDxYCHwAFAjQwZGQCAw8PFgIfAAUDMi41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATFkZAIIDw8WBh8ABQI2MB8NCiUfDgIIZGQCCQ8PFgIfAAUDMi41ZGQCKA9kFhRmDw8WAh8ABQVIMTIxNmRkAgEPDxYCHwAFEuaVsOWtl+S/oeWPt+WkhOeQhmRkAgIPDxYCHwAFAjQ4ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOW/heS/ruivvmRkAgUPDxYCHwAFA+aYr2RkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQExZGQCCA8PFgYfAAUCNjAfDQolHw4CCGRkAgkPDxYCHwAFATNkZAIpD2QWFGYPDxYCHwAFBUgxMjI0ZGQCAQ8PFgIfAAUV55S156OB5Zy65LiO55S156OB5rOiZGQCAg8PFgIfAAUCNDBkZAIDDw8WAh8ABQMyLjVkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjYxZGQCCQ8PFgIfAAUDMi41ZGQCKg9kFhRmDw8WAh8ABQVIMTI2N2RkAgEPDxYCHwAFD+S/oeaBr+iuuuWfuuehgGRkAgIPDxYCHwAFAjQwZGQCAw8PFgIfAAUDMi41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4N2RkAgkPDxYCHwAFAzIuNWRkAisPZBYUZg8PFgIfAAUFSDgwNzhkZAIBDw8WAh8ABRvmlbDlrZfnlLXot6/kuI7pgLvovpHorr7orqFkZAICDw8WAh8ABQI0OGRkAgMPDxYCHwAFATNkZAIEDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAIFDw8WAh8ABQPmmK9kZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYGHwAFAjI0Hw0KjQEfDgIIZGQCCQ8PFgIfAAUBMGRkAiwPZBYOZg8PFgIfAAUFRjAwMTZkZAIBDw8WAh8ABQzmlbDlgLzliIbmnpBkZAICDw8WAh8ABQIyNGRkAgMPDxYCHwAFAzEuNWRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOmAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAggPDxYGHwAFCeacquS/ruS5oB8NCo0BHw4CCGRkAi0PZBYOZg8PFgIfAAUFSDEwMTBkZAIBDw8WAh8ABRBKYXZh56iL5bqP6K6+6K6hZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCLg9kFg5mDw8WAh8ABQVIMTA2MmRkAgEPDxYCHwAFHemdouWQkeWvueixoeeoi+W6j+iuvuiuoShDKyspZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCLw9kFhRmDw8WAh8ABQVIMTEwNGRkAgEPDxYCHwAFFeW+ruazouaKgOacr+S4juWkqee6v2RkAgIPDxYCHwAFAjMyZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muW5s+WPsOmAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODBkZAIJDw8WAh8ABQEyZGQCMA9kFg5mDw8WAh8ABQVRMDAxMGRkAgEPDxYCHwAFIee9kee7nOS/oeaBr+i1hOa6kOW8gOWPkeS4juWIqeeUqGRkAgIPDxYCHwAFAjI0ZGQCAw8PFgIfAAUDMS41ZGQCBA8PFgIfAAUV5LiT5Lia5bmz5Y+w6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCMQ9kFhRmDw8WAh8ABQVGNzAwMWRkAgEPDxYCHwAFFOeJqeeQhuWunumqjOKFoCjkuIApZGQCAg8PFgIfAAUCMjRkZAIDDw8WAh8ABQMxLjVkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjgwZGQCCQ8PFgIfAAUDMS41ZGQCMg9kFhRmDw8WAh8ABQVGNzAwMmRkAgEPDxYCHwAFFOeJqeeQhuWunumqjOKFoCjkuowpZGQCAg8PFgIfAAUCMjRkZAIDDw8WAh8ABQMxLjVkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBM2RkAggPDxYGHwAFAjYwHw0KJR8OAghkZAIJDw8WAh8ABQMxLjVkZAIzD2QWFGYPDxYCHwAFBUgxMTEwZGQCAQ8PFgIfAAUS546w5Luj5Lqk5o2i5Y6f55CGZGQCAg8PFgIfAAUCNDBkZAIDDw8WAh8ABQMyLjVkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE1ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjY2ZGQCCQ8PFgIfAAUDMi41ZGQCNA9kFhRmDw8WAh8ABQVIMTEyNGRkAgEPDxYCHwAFDOenu+WKqOmAmuS/oWRkAgIPDxYCHwAFAjQ4ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFFeS4k+S4muaooeWdl+W/heS/ruivvmRkAgUPDxYCHwAFA+aYr2RkAgYPDxYCHwAFBDIwMTVkZAIHDw8WAh8ABQExZGQCCA8PFgYfAAUCNjAfDQolHw4CCGRkAgkPDxYCHwAFATNkZAI1D2QWFGYPDxYCHwAFBUgxMjU3ZGQCAQ8PFgIfAAUaTXVsdGlzaW3nlLXlrZDmioDmnK/orr7orqFkZAICDw8WAh8ABQIxNmRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjg5ZGQCCQ8PFgIfAAUBMWRkAjYPZBYUZg8PFgIfAAUFSDEyNjhkZAIBDw8WAh8ABRLpgJrkv6Hnp5HmioDoi7Hor61kZAICDw8WAh8ABQIxNmRkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE1ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjg1ZGQCCQ8PFgIfAAUBMWRkAjcPZBYOZg8PFgIfAAUFSDgwMDJkZAIBDw8WAh8ABQzmr5XkuJrorr7orqFkZAICDw8WAh8ABQMxMndkZAIDDw8WAh8ABQIxMmRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+W/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAggPDxYGHwAFCeacquS/ruS5oB8NCo0BHw4CCGRkAjgPZBYUZg8PFgIfAAUFSDgwMjNkZAIBDw8WAh8ABRLpgJrkv6Hljp/nkIblrp7pqoxkZAICDw8WAh8ABQE4ZGQCAw8PFgIfAAUDMC41ZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI4MWRkAgkPDxYCHwAFAzAuNWRkAjkPZBYUZg8PFgIfAAUFSDgwMzNkZAIBDw8WAh8ABSFQcm90ZWzkuI7nlLXlrZDns7vnu5/or77nqIvorr7orqFkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE1ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjgwZGQCCQ8PFgIfAAUBMmRkAjoPZBYUZg8PFgIfAAUFSDgwNDdkZAIBDw8WAh8ABRVEU1Dns7vnu5/or77nqIvorr7orqFkZAICDw8WAh8ABQIxd2RkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjkyZGQCCQ8PFgIfAAUBMWRkAjsPZBYUZg8PFgIfAAUFSDgwNDhkZAIBDw8WAh8ABR7mlbDlrZfpgJrkv6Hns7vnu5/or77nqIvorr7orqFkZAICDw8WAh8ABQIxd2RkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjgyZGQCCQ8PFgIfAAUBMWRkAjwPZBYUZg8PFgIfAAUFSDgwNjlkZAIBDw8WAh8ABSHpgJrkv6HnlLXlrZDnur/ot6/mtYvph4/kuI7lrp7pqoxkZAICDw8WAh8ABQIxd2RkAgMPDxYCHwAFATFkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjc4ZGQCCQ8PFgIfAAUBMWRkAj0PZBYUZg8PFgIfAAUFSDgwODhkZAIBDw8WAh8ABR9GUEdB5LiO5pWw5a2X6YC76L6R6K++56iL6K6+6K6hZGQCAg8PFgIfAAUCMjRkZAIDDw8WAh8ABQMxLjVkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDEzZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjgyZGQCCQ8PFgIfAAUDMS41ZGQCPg9kFhRmDw8WAh8ABQVIODA5MGRkAgEPDxYCHwAFHkFWUuWNleeJh+acuuW6lOeUqOivvueoi+iuvuiuoWRkAgIPDxYCHwAFAjQ4ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFFeS4k+S4muaooeWdl+W/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODFkZAIJDw8WAh8ABQEzZGQCPw9kFhRmDw8WAh8ABQVIODA5MmRkAgEPDxYCHwAFIU1BVExBQuS4juS/oeWPt+WkhOeQhuivvueoi+iuvuiuoWRkAgIPDxYCHwAFAjF3ZGQCAw8PFgIfAAUBMWRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+W/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCOTFkZAIJDw8WAh8ABQExZGQCQA9kFhRmDw8WAh8ABQVIODA5M2RkAgEPDxYCHwAFJueUteWtkOe6v+i3r+ivvueoi+iuvuiuoSjkvY7jgIHpq5jpopEpZGQCAg8PFgIfAAUCMXdkZAIDDw8WAh8ABQExZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI3NWRkAgkPDxYCHwAFATFkZAJBD2QWFGYPDxYCHwAFBUg4MDk0ZGQCAQ8PFgIfAAUdRFNQ5oqA5pyv5LiO5a6e6aqMKOWQq+eQhuiuuilkZAICDw8WAh8ABQIyNGRkAgMPDxYCHwAFAzEuNWRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+W/heS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODRkZAIJDw8WAh8ABQMxLjVkZAJCD2QWFGYPDxYCHwAFBUg4MDk1ZGQCAQ8PFgIfAAUe5pWw5a2X5Zu+5YOP5aSE55CG6K++56iL6K6+6K6hZGQCAg8PFgIfAAUCMTZkZAIDDw8WAh8ABQExZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X5b+F5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI4NmRkAgkPDxYCHwAFATFkZAJDD2QWDmYPDxYCHwAFBUgxMDU5ZGQCAQ8PFgIfAAUP5o6l5YWl572R5oqA5pyvZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCRA9kFhRmDw8WAh8ABQVIMTA2OWRkAgEPDxYCHwAFHuW1jOWFpeW8j+ezu+e7n+WOn+eQhuS4juiuvuiuoWRkAgIPDxYCHwAFAjQwZGQCAw8PFgIfAAUDMi41ZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNWRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI3M2RkAgkPDxYCHwAFAzIuNWRkAkUPZBYOZg8PFgIfAAUFSDExMDBkZAIBDw8WAh8ABRjnvZHnu5zpgJrkv6HnvJbnqIvmioDmnK9kZAICDw8WAh8ABQI0MGRkAgMPDxYCHwAFAzIuNWRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAggPDxYGHwAFCeacquS/ruS5oB8NCo0BHw4CCGRkAkYPZBYUZg8PFgIfAAUFSDExNDhkZAIBDw8WAh8ABRXpgJrkv6Hlt6XnqIvmpoLpooTnrpdkZAICDw8WAh8ABQE4ZGQCAw8PFgIfAAUDMC41ZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNWRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4MGRkAgkPDxYCHwAFAzAuNWRkAkcPZBYUZg8PFgIfAAUFSDExNDlkZAIBDw8WAh8ABQzpgJrkv6HnlLXmupBkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZfpgInkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBM2RkAggPDxYCHwAFAjg1ZGQCCQ8PFgIfAAUBMmRkAkgPZBYUZg8PFgIfAAUFSDExNTBkZAIBDw8WAh8ABRvml6Dnur/nvZHnu5zop4TliJLkuI7kvJjljJZkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZfpgInkv67or75kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE1ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjg1ZGQCCQ8PFgIfAAUBMmRkAkkPZBYUZg8PFgIfAAUFSDEyMTFkZAIBDw8WAh8ABRjkvKDmhJ/lmajkuI7mo4DmtYvmioDmnK9kZAICDw8WAh8ABQIyNGRkAgMPDxYCHwAFAzEuNWRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCNzBkZAIJDw8WAh8ABQMxLjVkZAJKD2QWFGYPDxYCHwAFBUgxMjI2ZGQCAQ8PFgIfAAUS5bCE6aKR55S16Lev5YiG5p6QZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNGRkAgcPDxYCHwAFATNkZAIIDw8WAh8ABQI2MWRkAgkPDxYCHwAFATJkZAJLD2QWDmYPDxYCHwAFBUgxMjY5ZGQCAQ8PFgIfAAUV6YCa5L+h572R55CG6K665Z+656GAZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCTA9kFg5mDw8WAh8ABQVIMTI3MGRkAgEPDxYCHwAFHSjnoJTorqgp5aSa5aqS5L2T6YCa5L+h5oqA5pyvZGQCAg8PFgIfAAUCMzJkZAIDDw8WAh8ABQEyZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCCA8PFgYfAAUJ5pyq5L+u5LmgHw0KjQEfDgIIZGQCTQ9kFhRmDw8WAh8ABQVIMTI3MWRkAgEPDxYCHwAFGijnoJTorqgp6YCa5L+h5YmN5rK/5oqA5pyvZGQCAg8PFgIfAAUCMTZkZAIDDw8WAh8ABQExZGQCBA8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNWRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4OWRkAgkPDxYCHwAFATFkZAJOD2QWFGYPDxYCHwAFBUgxMjcyZGQCAQ8PFgIfAAUZRlBHQeS4jumAmuS/oeezu+e7n+iuvuiuoWRkAgIPDxYCHwAFAjE2ZGQCAw8PFgIfAAUBMWRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTRkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODJkZAIJDw8WAh8ABQExZGQCTw9kFg5mDw8WAh8ABQVIODAwM2RkAgEPDxYCHwAFDOavleS4muWunuS5oGRkAgIPDxYCHwAFAjR3ZGQCAw8PFgIfAAUBNGRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAggPDxYGHwAFCeacquS/ruS5oB8NCo0BHw4CCGRkAlAPZBYOZg8PFgIfAAUFSDgwNTZkZAIBDw8WAh8ABRjnlLXkv6HkuJrliqHova/ku7blvIDlj5FkZAICDw8WAh8ABQIzMmRkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZfpgInkv67or75kZAIFDw8WAh8ABQPlkKZkZAIIDw8WBh8ABQnmnKrkv67kuaAfDQqNAR8OAghkZAJRD2QWFGYPDxYCHwAFBUg4MDgzZGQCAQ8PFgIfAAUT6aG555uu57u85ZCI5a6e6Le1MWRkAgIPDxYCHwAFAjJ3ZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTVkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCOTBkZAIJDw8WAh8ABQEyZGQCUg9kFg5mDw8WAh8ABQVIODA4NGRkAgEPDxYCHwAFE+mhueebrue7vOWQiOWunui3tTJkZAICDw8WAh8ABQIyd2RkAgMPDxYCHwAFATJkZAIEDw8WAh8ABRXkuJPkuJrmqKHlnZfpgInkv67or75kZAIFDw8WAh8ABQPlkKZkZAIIDw8WBh8ABQnmnKrkv67kuaAfDQqNAR8OAghkZAJTD2QWFGYPDxYCHwAFBUg4MDk2ZGQCAQ8PFgIfAAUT6aG555uu57u85ZCI5a6e6Le1M2RkAgIPDxYCHwAFAjJ3ZGQCAw8PFgIfAAUBMmRkAgQPDxYCHwAFFeS4k+S4muaooeWdl+mAieS/ruivvmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTVkZAIHDw8WAh8ABQEzZGQCCA8PFgIfAAUCODZkZAIJDw8WAh8ABQEyZGQCVA9kFhRmDw8WAh8ABQVRMDAwMWRkAgEPDxYCHwAFFOWwseS4muaMh+WvvOivvijkuIApZGQCAg8PFgIfAAUBOGRkAgMPDxYCHwAFAzAuNWRkAgQPDxYCHwAFEue0oOi0qOaLk+WxleW/heS/rmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTNkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCNzFkZAIJDw8WAh8ABQMwLjVkZAJVD2QWFGYPDxYCHwAFBVEwMDAyZGQCAQ8PFgIfAAUU5bCx5Lia5oyH5a+86K++KOS6jClkZAICDw8WAh8ABQE4ZGQCAw8PFgIfAAUDMC41ZGQCBA8PFgIfAAUS57Sg6LSo5ouT5bGV5b+F5L+uZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxNWRkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI3OGRkAgkPDxYCHwAFAzAuNWRkAlYPZBYUZg8PFgIfAAUFWDAwMDFkZAIBDw8WAh8ABRPlt6XnqIvln7rnoYDorq3nu4NJZGQCAg8PFgIfAAUCMXdkZAIDDw8WAh8ABQExZGQCBA8PFgIfAAUS57Sg6LSo5ouT5bGV5b+F5L+uZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI5M2RkAgkPDxYCHwAFATFkZAJXD2QWFGYPDxYCHwAFBVgwMDA0ZGQCAQ8PFgIfAAUV5bel56iL5Z+656GA6K6t57uD4oWhZGQCAg8PFgIfAAUCMXdkZAIDDw8WAh8ABQExZGQCBA8PFgIfAAUS57Sg6LSo5ouT5bGV5b+F5L+uZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4MWRkAgkPDxYCHwAFATFkZAJYD2QWFGYPDxYCHwAFBVkwMDA1ZGQCAQ8PFgIfAAUU5b2i5Yq/5LiO5pS/562WKOS4gClkZAICDw8WAh8ABQE4ZGQCAw8PFgIfAAUDMC41ZGQCBA8PFgIfAAUS57Sg6LSo5ouT5bGV5b+F5L+uZGQCBQ8PFgIfAAUD5ZCmZGQCBg8PFgIfAAUEMjAxM2RkAgcPDxYCHwAFATFkZAIIDw8WAh8ABQI4MGRkAgkPDxYCHwAFAzAuNWRkAlkPZBYUZg8PFgIfAAUFWTAwMDZkZAIBDw8WAh8ABRTlvaLlir/kuI7mlL/nrZYo5LqMKWRkAgIPDxYCHwAFAThkZAIDDw8WAh8ABQMwLjVkZAIEDw8WAh8ABRLntKDotKjmi5PlsZXlv4Xkv65kZAIFDw8WAh8ABQPlkKZkZAIGDw8WAh8ABQQyMDE0ZGQCBw8PFgIfAAUBMWRkAggPDxYCHwAFAjkwZGQCCQ8PFgIfAAUDMC41ZGQCWg9kFhRmDw8WAh8ABQVZMDAwN2RkAgEPDxYCHwAFFOW9ouWKv+S4juaUv+etlijkuIkpZGQCAg8PFgIfAAUBOGRkAgMPDxYCHwAFAzAuNWRkAgQPDxYCHwAFEue0oOi0qOaLk+WxleW/heS/rmRkAgUPDxYCHwAFA+WQpmRkAgYPDxYCHwAFBDIwMTVkZAIHDw8WAh8ABQExZGQCCA8PFgIfAAUCODdkZAIJDw8WAh8ABQMwLjVkZAJbDw8WAh4HVmlzaWJsZWhkZAIDDzwrAA0BAA8WCh4IUGFnZVNpemUCFB8BZx8KAgEfCwIHHwxlZBYCZg9kFhACAQ9kFggCAQ8PFgIfAAUV5YWo5qCh5YWs5YWx5b+F5L+u6K++ZGQCAg8PFgIfAAUCNDJkZAIDDw8WAh8ABQI0MmRkAgQPDxYCHwAFATBkZAICD2QWCAIBDw8WAh8ABRXlhajmoKHlhazlhbHpgInkv67or75kZAICDw8WAh8ABQE0ZGQCAw8PFgIfAAUBNWRkAgQPDxYCHwAFATFkZAIDD2QWCAIBDw8WAh8ABRXkuJPkuJrlubPlj7Dlv4Xkv67or75kZAICDw8WAh8ABQQ2My41ZGQCAw8PFgIfAAUCNTRkZAIEDw8WBh8ABQQtOS41HglGb3JlQ29sb3IKjQEfDgIEZGQCBA9kFggCAQ8PFgIfAAUV5LiT5Lia5bmz5Y+w6YCJ5L+u6K++ZGQCAg8PFgIfAAUDMy41ZGQCAw8PFgIfAAUBMmRkAgQPDxYGHwAFBC0xLjUfEQqNAR8OAgRkZAIFD2QWCAIBDw8WAh8ABRXkuJPkuJrmqKHlnZflv4Xkv67or75kZAICDw8WAh8ABQI0OGRkAgMPDxYCHwAFAjI1ZGQCBA8PFgYfAAUDLTIzHxEKjQEfDgIEZGQCBg9kFggCAQ8PFgIfAAUV5LiT5Lia5qih5Z2X6YCJ5L+u6K++ZGQCAg8PFgIfAAUCMTJkZAIDDw8WAh8ABQQxNi41ZGQCBA8PFgIfAAUDNC41ZGQCBw9kFggCAQ8PFgIfAAUP6K++5aSW5b+F5L+u6K++ZGQCAg8PFgIfAAUBMGRkAgMPDxYCHwAFATBkZAIEDw8WAh8ABQEwZGQCCA8PFgIfD2hkZBgDBSZjdGwwMCRNYWluQ29udGVudFBsYWNlSG9sZGVyJEdyaWRWaWV3Mg88KwAIAgYVAQdPcmRlcklEBxQrAAcUKwABAgEUKwABAgIUKwABAgMUKwABAgQUKwABAgUUKwABAgYUKwABAgdkBSZjdGwwMCRNYWluQ29udGVudFBsYWNlSG9sZGVyJEdyaWRTY29yZQ9nZAULY3RsMDAkTWVudTIPD2QFHeWtpuS4mumihOitplzil4Yg5a2m5Lia5q+U5a+5ZCZkHywCtHPF3gxuaeImdfTvhjTb" />
</div>





        <div>
            <table width="100%" height="102" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="topbj_bgimage">
                        <table width="100%" height="102" border="0" cellpadding="0" cellspacing="0">
                            <tr>
                                <td colspan="3" class="top1_bgimage" width="100%" height="71">
                                </td>
                            </tr>
                            <tr>
                                <td width="16%" class="top2_bgimage">
                                    <table width="100%" height="31" border="0" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td height="3">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                &nbsp;&nbsp;&nbsp;&nbsp;『<span id="ctl00_lblSignIn">2012136121吴化吉</span>』
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td align="left" class="top3_bgimage">
                                    <table width="100%" height="31" border="0" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td width="9%">
                                            </td>
                                            <td>
                                                <table height="31" border="0" cellpadding="0" cellspacing="0">

                                               <tr>
                                                        <td rowspan="2"  width="0" height="31">
                                                        </td>
                                                        <td height="8">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td >
                                                            <a href="#ctl00_Menu2_SkipLink" style="display:inline-block;height:1px;width:1px;"><img src="/jwc_glxt/WebResource.axd?d=p-y_zQv1oWCYLLME-mCiOQ2&amp;t=634184281466406250" alt="Skip Navigation Links" style="border-width:0px;" /></a><div id="ctl00_Menu2">
	<span title="学业预警"><a class="ctl00_Menu2_1" href="javascript:__doPostBack('ctl00$Menu2','o学业预警')">学业预警<img src="/jwc_glxt/WebResource.axd?d=s6sDJEXkR4ATKAlea15GU041wWuBm3nobrglLZFzuMw1&amp;t=634184281466406250" alt="Expand 学业预警" align="absmiddle" style="border-width:0px;" /></a></span>
</div><a name="ctl00_Menu2_SkipLink"></a>

                                                          </td>
                                                          <td>
                                                          <a href="#ctl00_Menu1_SkipLink" style="display:inline-block;height:1px;width:1px;"><img src="/jwc_glxt/WebResource.axd?d=p-y_zQv1oWCYLLME-mCiOQ2&amp;t=634184281466406250" alt="Skip Navigation Links" style="border-width:0px;" /></a><div id="ctl00_Menu1">
	<span title="各类通知及事务"><a class="ctl00_Menu1_1" href="/jwc_glxt/Stu_Notice/Notice_Query.aspx"> | | 即时事务</a></span> <span title="学生选课"><a class="ctl00_Menu1_1" href="javascript:__doPostBack('ctl00$Menu1','o || || 学生选课')"> | | 学生选课<img src="/jwc_glxt/WebResource.axd?d=s6sDJEXkR4ATKAlea15GU041wWuBm3nobrglLZFzuMw1&amp;t=634184281466406250" alt="Expand  | | 学生选课" align="absmiddle" style="border-width:0px;" /></a></span> <span title="学生成绩查询"><a class="ctl00_Menu1_1" href="javascript:__doPostBack('ctl00$Menu1','o || || 成绩查询')"> | | 成绩查询<img src="/jwc_glxt/WebResource.axd?d=s6sDJEXkR4ATKAlea15GU041wWuBm3nobrglLZFzuMw1&amp;t=634184281466406250" alt="Expand  | | 成绩查询" align="absmiddle" style="border-width:0px;" /></a></span> <span title="各类报名"><a class="ctl00_Menu1_1" href="javascript:__doPostBack('ctl00$Menu1','o || || 各类报名')"> | | 各类报名<img src="/jwc_glxt/WebResource.axd?d=s6sDJEXkR4ATKAlea15GU041wWuBm3nobrglLZFzuMw1&amp;t=634184281466406250" alt="Expand  | | 各类报名" align="absmiddle" style="border-width:0px;" /></a></span> <span title="学生评教"><a class="ctl00_Menu1_1" href="/jwc_glxt/Stu_Assess/Stu_Assess.aspx"> | | 学生评教</a></span> <span title="个人信息"><a class="ctl00_Menu1_1" href="javascript:__doPostBack('ctl00$Menu1','o || || 个人信息')"> | | 个人信息<img src="/jwc_glxt/WebResource.axd?d=s6sDJEXkR4ATKAlea15GU041wWuBm3nobrglLZFzuMw1&amp;t=634184281466406250" alt="Expand  | | 个人信息" align="absmiddle" style="border-width:0px;" /></a></span>
</div><a name="ctl00_Menu1_SkipLink"></a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                            <td>
                                                <table height="31" border="0" cellpadding="0" cellspacing="0">
                                                    <tr>
                                                        <td rowspan="2"  width="0" height="31">
                                                        </td>
                                                        <td height="8">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                            <td>
                                                <table height="31" border="0" cellpadding="0" cellspacing="0">
                                                    <tr>
                                                        <td rowspan="2" class="top4_bgimage" width="39" height="31">
                                                        </td>
                                                        <td height="8" width="60">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <a href="../Login.aspx?xttc=1" target="_top">退出</a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td width="6%" class="top5_bgimage" height="31">
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
        <div style="text-align: center" class="table_bgcolor">
            <div  style="width: 96%" >


    <table class="table_bordercolor" border="0" cellpadding="0" cellspacing="0" style="height: 0px;width: 100%">
     <caption><h2>学生培养计划与实际修习情况比对</h2></caption>

    </table>

    <div>
	<table class="GridViewStyle" cellspacing="0" rules="all" border="1" id="ctl00_MainContentPlaceHolder_GridScore" style="border-collapse:collapse;">
		<tr class="HeaderStyle">
			<th scope="col">课程编号</th><th scope="col">课程名称</th><th scope="col">课程学时</th><th scope="col">课程学分</th><th scope="col">课程类型</th><th scope="col">学位课</th><th scope="col">修读学年</th><th scope="col">修读学期</th><th scope="col">最高成绩</th><th scope="col">获得学分</th>
		</tr><tr>
			<td>G0001</td><td>体育</td><td>30</td><td>1</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>3</td><td>79</td><td>1</td>
		</tr><tr>
			<td>G0001</td><td>体育</td><td>30</td><td>1</td><td>全校公共必修课</td><td>否</td><td>2014</td><td>1</td><td>65</td><td>1</td>
		</tr><tr>
			<td>G0001</td><td>体育</td><td>30</td><td>1</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>65</td><td>1</td>
		</tr><tr>
			<td>G0001</td><td>体育</td><td>30</td><td>1</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>1</td><td>65</td><td>1</td>
		</tr><tr>
			<td>H0001</td><td>计算机基础</td><td>48</td><td>3</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>84</td><td>3</td>
		</tr><tr>
			<td>H1005</td><td>C语言程序设计</td><td>64</td><td>4</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>60</td><td>4</td>
		</tr><tr>
			<td>P0001</td><td>大学英语1级听说</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>78</td><td>2</td>
		</tr><tr>
			<td>P0002</td><td>大学英语1级读写</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>66</td><td>2</td>
		</tr><tr>
			<td>P0003</td><td>大学英语2级听说</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>1</td><td>69</td><td>2</td>
		</tr><tr>
			<td>P0004</td><td>大学英语2级读写</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>1</td><td>69</td><td>2</td>
		</tr><tr>
			<td>P0005</td><td>大学英语3级听说</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>3</td><td style="background-color:Blue;">60</td><td>2</td>
		</tr><tr>
			<td>P0006</td><td>大学英语3级读写</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>3</td><td>69</td><td>2</td>
		</tr><tr>
			<td>P0007</td><td>大学英语4级听说</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2014</td><td>1</td><td style="background-color:Blue;">60</td><td>2</td>
		</tr><tr>
			<td>P0008</td><td>大学英语4级读写</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2014</td><td>1</td><td>74</td><td>2</td>
		</tr><tr>
			<td>P1202</td><td>大学英语5级听说</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>P1203</td><td>大学英语5级读写</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>Q0005</td><td>军事理论</td><td>8</td><td>0.5</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>78</td><td>0.5</td>
		</tr><tr>
			<td>Q0006</td><td>军事训练</td><td>2w</td><td>2.5</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>88</td><td>2.5</td>
		</tr><tr>
			<td>Y0001</td><td>马克思主义基本原理</td><td>48</td><td>3</td><td>全校公共必修课</td><td>否</td><td>2012</td><td>3</td><td>76</td><td>3</td>
		</tr><tr>
			<td>Y0002</td><td>中国近现代史纲要</td><td>32</td><td>2</td><td>全校公共必修课</td><td>否</td><td>2014</td><td>1</td><td>71</td><td>2</td>
		</tr><tr>
			<td>Y0004</td><td>毛泽东思想和中国特色社会主义理论体系概论</td><td>96</td><td>4</td><td>全校公共必修课</td><td>是</td><td>2013</td><td>3</td><td>84</td><td>4</td>
		</tr><tr>
			<td>Y0012</td><td>思想道德修养与法律基础</td><td>48</td><td>3</td><td>全校公共必修课</td><td>否</td><td>2013</td><td>1</td><td>83</td><td>3</td>
		</tr><tr>
			<td>C1146</td><td>电路与模拟电子技术</td><td>72</td><td>4.5</td><td>专业平台必修课</td><td>否</td><td>2014</td><td>1</td><td>65</td><td>4.5</td>
		</tr><tr>
			<td>C8073</td><td>电路与模拟电子技术实验</td><td>16</td><td>1</td><td>专业平台必修课</td><td>否</td><td>2012</td><td>3</td><td>88</td><td>1</td>
		</tr><tr>
			<td>F0001</td><td>高等数学Ⅰ(一)</td><td>88</td><td>5.5</td><td>专业平台必修课</td><td>是</td><td>2012</td><td>3</td><td>68</td><td>5.5</td>
		</tr><tr>
			<td>F0002</td><td>高等数学Ⅰ(二)</td><td>88</td><td>5.5</td><td>专业平台必修课</td><td>是</td><td>2013</td><td>1</td><td>60</td><td>5.5</td>
		</tr><tr>
			<td>F0007</td><td>线性代数Ⅰ</td><td>32</td><td>2</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>1</td><td>69</td><td>2</td>
		</tr><tr>
			<td>F0009</td><td>概率统计Ⅰ</td><td>40</td><td>2.5</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>3</td><td>62</td><td>2.5</td>
		</tr><tr>
			<td>F0012</td><td>大学物理Ⅰ(一)</td><td>56</td><td>3.5</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>1</td><td>61</td><td>3.5</td>
		</tr><tr>
			<td>F0013</td><td>大学物理Ⅰ(二)</td><td>48</td><td>3</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>3</td><td>65</td><td>3</td>
		</tr><tr>
			<td>H1049</td><td>计算机网络</td><td>48</td><td>3</td><td>专业平台必修课</td><td>是</td><td>2015</td><td>1</td><td>66</td><td>3</td>
		</tr><tr>
			<td>H1086</td><td>数据结构</td><td>32</td><td>2</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>1</td><td style="background-color:Red;">41</td><td>0</td>
		</tr><tr>
			<td>H1091</td><td>数字图像处理</td><td>32</td><td>2</td><td>专业平台必修课</td><td>否</td><td>2014</td><td>3</td><td>83</td><td>2</td>
		</tr><tr>
			<td>H1094</td><td>随机信号分析</td><td>32</td><td>2</td><td>专业平台必修课</td><td>否</td><td>2014</td><td>1</td><td>63</td><td>2</td>
		</tr><tr>
			<td>H1096</td><td>通信原理Ⅰ</td><td>72</td><td>4.5</td><td>专业平台必修课</td><td>是</td><td>2014</td><td>3</td><td style="background-color:Blue;">60</td><td>4.5</td>
		</tr><tr>
			<td>H1106</td><td>微型计算机技术</td><td>64</td><td>4</td><td>专业平台必修课</td><td>是</td><td>2013</td><td>3</td><td style="background-color:Blue;">60</td><td>4</td>
		</tr><tr>
			<td>H1113</td><td>信号与系统</td><td>72</td><td>4.5</td><td>专业平台必修课</td><td>是</td><td>2013</td><td>3</td><td style="background-color:Red;">27</td><td>0</td>
		</tr><tr>
			<td>H1199</td><td>通信工程学科概论(双语)</td><td>8</td><td>0.5</td><td>专业平台必修课</td><td>否</td><td>2012</td><td>3</td><td>94</td><td>0.5</td>
		</tr><tr>
			<td>H1215</td><td>通信电子线路</td><td>40</td><td>2.5</td><td>专业平台必修课</td><td>否</td><td>2014</td><td>1</td><td style="background-color:Blue;">60</td><td>2.5</td>
		</tr><tr>
			<td>H1216</td><td>数字信号处理</td><td>48</td><td>3</td><td>专业平台必修课</td><td>是</td><td>2014</td><td>1</td><td style="background-color:Blue;">60</td><td>3</td>
		</tr><tr>
			<td>H1224</td><td>电磁场与电磁波</td><td>40</td><td>2.5</td><td>专业平台必修课</td><td>否</td><td>2013</td><td>3</td><td>61</td><td>2.5</td>
		</tr><tr>
			<td>H1267</td><td>信息论基础</td><td>40</td><td>2.5</td><td>专业平台必修课</td><td>否</td><td>2014</td><td>1</td><td>87</td><td>2.5</td>
		</tr><tr>
			<td>H8078</td><td>数字电路与逻辑设计</td><td>48</td><td>3</td><td>专业平台必修课</td><td>是</td><td>2013</td><td>1</td><td style="background-color:Red;">24</td><td>0</td>
		</tr><tr>
			<td>F0016</td><td>数值分析</td><td>24</td><td>1.5</td><td>专业平台选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1010</td><td>Java程序设计</td><td>32</td><td>2</td><td>专业平台选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1062</td><td>面向对象程序设计(C++)</td><td>32</td><td>2</td><td>专业平台选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1104</td><td>微波技术与天线</td><td>32</td><td>2</td><td>专业平台选修课</td><td>否</td><td>2013</td><td>3</td><td>80</td><td>2</td>
		</tr><tr>
			<td>Q0010</td><td>网络信息资源开发与利用</td><td>24</td><td>1.5</td><td>专业平台选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>F7001</td><td>物理实验Ⅰ(一)</td><td>24</td><td>1.5</td><td>专业模块必修课</td><td>否</td><td>2013</td><td>1</td><td>80</td><td>1.5</td>
		</tr><tr>
			<td>F7002</td><td>物理实验Ⅰ(二)</td><td>24</td><td>1.5</td><td>专业模块必修课</td><td>否</td><td>2013</td><td>3</td><td style="background-color:Blue;">60</td><td>1.5</td>
		</tr><tr>
			<td>H1110</td><td>现代交换原理</td><td>40</td><td>2.5</td><td>专业模块必修课</td><td>否</td><td>2015</td><td>1</td><td>66</td><td>2.5</td>
		</tr><tr>
			<td>H1124</td><td>移动通信</td><td>48</td><td>3</td><td>专业模块必修课</td><td>是</td><td>2015</td><td>1</td><td style="background-color:Blue;">60</td><td>3</td>
		</tr><tr>
			<td>H1257</td><td>Multisim电子技术设计</td><td>16</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2013</td><td>1</td><td>89</td><td>1</td>
		</tr><tr>
			<td>H1268</td><td>通信科技英语</td><td>16</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2015</td><td>1</td><td>85</td><td>1</td>
		</tr><tr>
			<td>H8002</td><td>毕业设计</td><td>12w</td><td>12</td><td>专业模块必修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H8023</td><td>通信原理实验</td><td>8</td><td>0.5</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>3</td><td>81</td><td>0.5</td>
		</tr><tr>
			<td>H8033</td><td>Protel与电子系统课程设计</td><td>32</td><td>2</td><td>专业模块必修课</td><td>否</td><td>2015</td><td>1</td><td>80</td><td>2</td>
		</tr><tr>
			<td>H8047</td><td>DSP系统课程设计</td><td>1w</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>3</td><td>92</td><td>1</td>
		</tr><tr>
			<td>H8048</td><td>数字通信系统课程设计</td><td>1w</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>3</td><td>82</td><td>1</td>
		</tr><tr>
			<td>H8069</td><td>通信电子线路测量与实验</td><td>1w</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>1</td><td>78</td><td>1</td>
		</tr><tr>
			<td>H8088</td><td>FPGA与数字逻辑课程设计</td><td>24</td><td>1.5</td><td>专业模块必修课</td><td>否</td><td>2013</td><td>1</td><td>82</td><td>1.5</td>
		</tr><tr>
			<td>H8090</td><td>AVR单片机应用课程设计</td><td>48</td><td>3</td><td>专业模块必修课</td><td>否</td><td>2013</td><td>3</td><td>81</td><td>3</td>
		</tr><tr>
			<td>H8092</td><td>MATLAB与信号处理课程设计</td><td>1w</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>1</td><td>91</td><td>1</td>
		</tr><tr>
			<td>H8093</td><td>电子线路课程设计(低、高频)</td><td>1w</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>1</td><td>75</td><td>1</td>
		</tr><tr>
			<td>H8094</td><td>DSP技术与实验(含理论)</td><td>24</td><td>1.5</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>3</td><td>84</td><td>1.5</td>
		</tr><tr>
			<td>H8095</td><td>数字图像处理课程设计</td><td>16</td><td>1</td><td>专业模块必修课</td><td>否</td><td>2014</td><td>3</td><td>86</td><td>1</td>
		</tr><tr>
			<td>H1059</td><td>接入网技术</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1069</td><td>嵌入式系统原理与设计</td><td>40</td><td>2.5</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>1</td><td>73</td><td>2.5</td>
		</tr><tr>
			<td>H1100</td><td>网络通信编程技术</td><td>40</td><td>2.5</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1148</td><td>通信工程概预算</td><td>8</td><td>0.5</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>1</td><td>80</td><td>0.5</td>
		</tr><tr>
			<td>H1149</td><td>通信电源</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td>2014</td><td>3</td><td>85</td><td>2</td>
		</tr><tr>
			<td>H1150</td><td>无线网络规划与优化</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>1</td><td>85</td><td>2</td>
		</tr><tr>
			<td>H1211</td><td>传感器与检测技术</td><td>24</td><td>1.5</td><td>专业模块选修课</td><td>否</td><td>2014</td><td>3</td><td>70</td><td>1.5</td>
		</tr><tr>
			<td>H1226</td><td>射频电路分析</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td>2014</td><td>3</td><td>61</td><td>2</td>
		</tr><tr>
			<td>H1269</td><td>通信网理论基础</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1270</td><td>(研讨)多媒体通信技术</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H1271</td><td>(研讨)通信前沿技术</td><td>16</td><td>1</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>1</td><td>89</td><td>1</td>
		</tr><tr>
			<td>H1272</td><td>FPGA与通信系统设计</td><td>16</td><td>1</td><td>专业模块选修课</td><td>否</td><td>2014</td><td>3</td><td>82</td><td>1</td>
		</tr><tr>
			<td>H8003</td><td>毕业实习</td><td>4w</td><td>4</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H8056</td><td>电信业务软件开发</td><td>32</td><td>2</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H8083</td><td>项目综合实践1</td><td>2w</td><td>2</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>1</td><td>90</td><td>2</td>
		</tr><tr>
			<td>H8084</td><td>项目综合实践2</td><td>2w</td><td>2</td><td>专业模块选修课</td><td>否</td><td></td><td></td><td style="background-color:Red;">未修习</td><td></td>
		</tr><tr>
			<td>H8096</td><td>项目综合实践3</td><td>2w</td><td>2</td><td>专业模块选修课</td><td>否</td><td>2015</td><td>3</td><td>86</td><td>2</td>
		</tr><tr>
			<td>Q0001</td><td>就业指导课(一)</td><td>8</td><td>0.5</td><td>素质拓展必修</td><td>否</td><td>2013</td><td>1</td><td>71</td><td>0.5</td>
		</tr><tr>
			<td>Q0002</td><td>就业指导课(二)</td><td>8</td><td>0.5</td><td>素质拓展必修</td><td>否</td><td>2015</td><td>1</td><td>78</td><td>0.5</td>
		</tr><tr>
			<td>X0001</td><td>工程基础训练I</td><td>1w</td><td>1</td><td>素质拓展必修</td><td>否</td><td>2013</td><td>1</td><td>93</td><td>1</td>
		</tr><tr>
			<td>X0004</td><td>工程基础训练Ⅱ</td><td>1w</td><td>1</td><td>素质拓展必修</td><td>否</td><td>2013</td><td>1</td><td>81</td><td>1</td>
		</tr><tr>
			<td>Y0005</td><td>形势与政策(一)</td><td>8</td><td>0.5</td><td>素质拓展必修</td><td>否</td><td>2013</td><td>1</td><td>80</td><td>0.5</td>
		</tr><tr>
			<td>Y0006</td><td>形势与政策(二)</td><td>8</td><td>0.5</td><td>素质拓展必修</td><td>否</td><td>2014</td><td>1</td><td>90</td><td>0.5</td>
		</tr><tr>
			<td>Y0007</td><td>形势与政策(三)</td><td>8</td><td>0.5</td><td>素质拓展必修</td><td>否</td><td>2015</td><td>1</td><td>87</td><td>0.5</td>
		</tr>
	</table>
</div>
    <br />
    <h2>各类课程应修/已修学分比对</h2>
        <div>
	<table class="GridViewStyle" cellspacing="0" rules="all" border="1" id="ctl00_MainContentPlaceHolder_GridView2" style="width:60%;border-collapse:collapse;">
		<tr class="HeaderStyle">
			<th scope="col">课程类型</th><th scope="col">应修学分</th><th scope="col">已获学分</th><th scope="col">差值</th>
		</tr><tr>
			<td>全校公共必修课</td><td>42</td><td>42</td><td>0</td>
		</tr><tr>
			<td>全校公共选修课</td><td>4</td><td>5</td><td>1</td>
		</tr><tr>
			<td>专业平台必修课</td><td>63.5</td><td>54</td><td style="color:Red;">-9.5</td>
		</tr><tr>
			<td>专业平台选修课</td><td>3.5</td><td>2</td><td style="color:Red;">-1.5</td>
		</tr><tr>
			<td>专业模块必修课</td><td>48</td><td>25</td><td style="color:Red;">-23</td>
		</tr><tr>
			<td>专业模块选修课</td><td>12</td><td>16.5</td><td>4.5</td>
		</tr><tr>
			<td>课外必修课</td><td>0</td><td>0</td><td>0</td>
		</tr>
	</table>
</div>

            </div>
        </div>

<div>

	<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
	<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEWBgLDzNHECgL5pJ/DDwKY5YbqAwLOyrSfCgKa/8n5CAKcv5WqDoyoOWzlMZ3qklpZtAflK0b9Zynt" />
</div>
<script type="text/javascript">
<!--
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
// -->
</script>

</form>
</body>
</html>

"""
# from bs4 import BeautifulSoup
#
# soup = BeautifulSoup(html_doc)
# tr_title = soup.find(attrs={'class':'HeaderStyle'})
#
# # print tr_title;
# plan = tr_title.find_next_siblings()
#
# {% if text %}
#                 {% for tiaomu in text %}
#                     <tr>
#                     {% for chengji in tiaomu %}
#                         <td>{{ chengji.string }}</td>
#                     {% endfor %}
#                     </tr>
#                 {% endfor %}
#             {% endif %}

# for tiaomu in plan:
#     for kecheng in tiaomu:
# 		print kecheng.string


a = 'None'